### ISSUE TITLE
Investigate data

### ISSUE THREAD

**Issue by MarkusKhoa** [demdecuong/vihealthbert#3]
I tried to run this code for experiments but got stuck with the "slot labels" in `slot_labels.txt` file which doesn't exist in this repo. Can you please tell me what it is and which components are used inside it?

**Comment by demdecuong** [comment]
Thank you @MarkusKhoa , thank you for trying out the repo.
Can you give me your steps in more details. (e.g: your folder, fine-tuning tasks, running script)

**Comment by LeKhaAn240805** [comment]
Anh ơi, em có thử chạy đoạn code tới đoạn 
python preprocess.py
Traceback (most recent call last):
  File "preprocess.py", line 34, in <module>
    test_src, test_trg = read_conll('../data/vinai_covid_word/test_word.conll')
  File "preprocess.py", line 12, in read_conll
    with open(path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../data/vinai_covid_word/test_word.conll'|

thì em cần phải tải data về thư mục hay sao ạ

**Comment by LeKhaAn240805** [comment]
Với lại cho em xin phép hỏi là anh hong có finetuning sẵn để sử dụng cho tác vụ NER cho ViHealthBert hay sao ạ, vì em không thấy a up trên huggingface
